# Generated by Django 4.2.4 on 2023-10-27 18:08

from django.db import migrations, models
import django.db.models.deletion
import musicapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicmindAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(blank=True, max_length=300, null=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to=musicapp.models.album_cover_directory_path)),
                ('mbid', models.CharField(blank=True, max_length=37, null=True)),
            ],
            options={
                'ordering': ['album'],
            },
        ),
        migrations.CreateModel(
            name='MusicmindArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=300)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='artist_covers')),
            ],
        ),
        migrations.CreateModel(
            name='MusicmindTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_file', models.FileField(upload_to=musicapp.models.audio_directory_path)),
                ('song_title', models.CharField(max_length=300)),
                ('soundsource_id', models.CharField(max_length=10)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mm_tracks', to='musicapp.musicmindalbum')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.musicmindartist')),
            ],
        ),
        migrations.CreateModel(
            name='MusicmindTrackDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=300, null=True)),
                ('mmTrack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.musicmindtrack', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='musicmindalbum',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mm_albums', to='musicapp.musicmindartist'),
        ),
    ]
